### ISSUE TITLE
Tasks: TOP => rbenv:validate error

### ISSUE THREAD

**Issue by sajjadmurtaza** [capistrano/rbenv#66]
✗ cap staging deploy 
DEBUG[600ca6ad] Running /usr/bin/env [ ! -d ~/.rbenv/versions/2.1.3 ] on abc-2.compute.amazonaws.com
DEBUG[600ca6ad] Command: [ ! -d ~/.rbenv/versions/2.1.3 ]
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host abc-2.compute.amazonaws.com: Connection timed out - connect(2) for "abc-2.compute.amazonaws.com" port 20

Errno::ETIMEDOUT: Connection timed out - connect(2) for "abc-2.compute.amazonaws.com" port 20

Tasks: TOP => rbenv:validate
(See full trace by running task with --trace)

Kindly guide me

**Comment by mattbrictson** [comment]
The error says you can't establish a network connection to abc-2.compute.amazonaws.com:20. Perhaps you mistyped your hostname or port number? In any case doesn't seem to be a capistrano-rbenv issue.

--

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).

**Comment by sureshcvh** [comment]
I am trying to deploy a staging serve by 
bundle exec cap staging deploy 

But this error, Any help please
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 10.65.11.22: invalid encoding


Caused by:
OpenSSL::PKey::EC::Point::Error: invalid encoding

Tasks: TOP => rbenv:validate
(See full trace by running task with --trace)
